# Generated by Django 2.0.4 on 2018-05-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seven',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
