# Generated by Django 2.0.4 on 2018-05-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_seven'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='seven',
        ),
    ]
