# Generated by Django 2.0.4 on 2018-05-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_newfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='recurrence_schedule',
        ),
        migrations.AddField(
            model_name='contact',
            name='recurrence_schedule_in_days',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
