# Generated by Django 2.0.4 on 2018-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20180430_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=1000)),
                ('last_contacted', models.DateField(auto_now_add=True)),
                ('recurrence_schedule_in_days', models.PositiveIntegerField(default=90)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
