# Generated by Django 2.0.4 on 2018-05-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_betacontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BetaContact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='info',
            new_name='contact_info',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='contact_name',
        ),
    ]
